### ISSUE TITLE
How to get all expand rows?

### ISSUE THREAD

**Issue by pengzhen-developer** [foolishchow/element-tree-grid#10]
Google translated : 

When I reload table data ,  i want to keep the row expanded. 

thanks.

**Comment by foolishchow** [comment]
there is no good way to do this , You may have to 'write down' those opened rows , and when reload , config then to `expandKey`

**Comment by pengzhen-developer** [comment]
@foolishchow  
Google translated :

Thanks for reply .

This is a way to achieve.  

But there are too many operations that can change the opened status.

This is a huge and unpredictable workload.

**Comment by foolishchow** [comment]
you can you `table.store.states.selection` to get all rows selected in `element`, it's provided in `element`

**Comment by foolishchow** [comment]
I'm sorry , `table.store.states.selection` is not the way to get all expanded
