### ISSUE TITLE
修改间距

### ISSUE THREAD

**Issue by Sunjian584970824** [foolishchow/element-tree-grid#11]
我如何修改第一层子元素和父元素就有一个间隔差呢？类似element-ui里面的tree组件那样的间距表现形式

**Comment by foolishchow** [comment]
你是要修改图标和文字之间的间距还是想让列左对齐？

**Comment by Kanchil** [comment]
element-ui的图标里没有文件夹的图标啊！！
![image](https://user-images.githubusercontent.com/20110220/29702004-a87b37c2-89a1-11e7-8dac-a789cf3ab101.png)
只有这些

**Comment by foolishchow** [comment]
`fileIcon` and `folderIcon` is custom for config `icon-class` this pack don't provide any style work;
`index-size` is provide to custom `indent`  in `0.1.1+`
