### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by jason65** [foolishchow/element-tree-grid#12]
我在Vue项目的main.js中如下引入：
import ElTreeGrid from 'element-tree-grid'
import ElTableTreeColumn from 'element-tree-grid/src/index.js'
Vue.component(ElTreeGrid.name, ElTreeGrid)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  ElTableTreeColumn,
  template: '<app/>',
  components: {
    app
  }
})
在npm run build的时候报错：如下：
ERROR in static/js/vendor.7887f3a6d40d515f31fd.js from UglifyJs
Unexpected token: punc (() [./~/.0.0.15@element-tree-grid/src/table-column.js:3,0][static/js/vendor.7887f3a6d40d515f31fd
.js:14339,14]

**Comment by foolishchow** [comment]
你是不是没有使用babel编译

**Comment by wuxusen** [comment]
UglifyJs无法解析ES6，解析失败后让babel去解析失败的包。
具体操作：
修改该目录下文件
-build
    --webpack.base.conf.js
修改后格式：
{
                test: /\.js$/,
                loader: 'babel-loader?cacheDirectory',
                include: [resolve('src'), resolve('test'),resolve('/node_modules/element-tree-grid/src/'),resolve('/node_modules/element-tree-grid/packages')]
}
