### ISSUE TITLE
expandAll 或者所有的父节点expanded属性值为true时，浏览器崩溃！

### ISSUE THREAD

**Issue by xiaojinge** [foolishchow/element-tree-grid#13]
我有几百条的数据量，想要初始化时展开所有的节点，在指定expandAll=true或每个父节点增加expanded=true属性后，treegrid组件出现无响应，浏览器崩溃的问题。

**Comment by nbsynch** [comment]
I have the same issue, though with only about 40 items.  If I set expandAll=true it will crash the browser.

**Comment by zhanghuanchong** [comment]
+1

**Comment by icai** [comment]
+1，改成异步好像没有问题

**Comment by foolishchow** [comment]
is fixed in 0.1.3 maybe
