### ISSUE TITLE
我也遇到了打包报错问题

### ISSUE THREAD

**Issue by heihei001** [foolishchow/element-tree-grid#17]
vue组件
`import ElTableTreeColumn from 'element-tree-grid/src/index.js'

  export default {
    name: '',
    components: {
      ElTableTreeColumn
    },
    data () {
      return {
        tableData: [],
        searchForm: {}
      }
    },
    computed: {},
    created () {
      this.loadMenu()
    },
    methods: {
      loadMenu () {
        this.axios.get('/brandhall/setting.menu/getlist').then(res => {
          this.tableData = res
        })
      },
      addMenu () {
        this.$router.push('add')
      },
      editMenu (id) {
        this.$router.push('edit/' + id)
      },
      deleteMenu (id) {
        this.$confirm('您确定要删除该菜单吗？', '提示', {
          type: 'warning'
        }).then(() => {
          this.axios.post('/brandhall/setting.menu/delete', {id: id}).then(res => {
            this.loadMenu()
          })
        }, () => {})
      }
    }
  }`
路由使用的懒加载

babel配置
`{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime",["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    },
    {
      "libraryName": "element-tree-grid"
    },
    {
      "libraryName": "vue-qrcode"
    }
  ]]],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
`

打包总是报错，
Unexpected token: punc (() [./~/_element-tree-grid@0.0.15@element-tree-grid/src/table-column.js:3,0][static/js/8.3f0de3281e3c143d7485.js:230,14]
请问下怎么解决啊

**Comment by foolishchow** [comment]
修改webpack的配置
```
{
test: /(\.js)$/,
loader:'babel-loader',
exclude: /node_modules\/[^(element\-tree\-grid)]/
}
```
