### ISSUE TITLE
how make tree grid expanded by default

### ISSUE THREAD

**Issue by neil-dang** [foolishchow/element-tree-grid#2]
as the title

**Comment by foolishchow** [comment]
currently there is no optional config to do this , next version will add .

**Comment by foolishchow** [comment]
@neil-dang  Sorry to tell you that this `prop` might have to be wait for days , currently I'm working on it.

**Comment by insub** [comment]
@foolishchow Is that have any api can make all node expanded? 
And, Thank for you work! Creat job!

**Comment by neil-dang** [comment]
@insub i am still waiting for this prop, but there is no update.

**Comment by foolishchow** [comment]
`expandAll` is the `prop` in `0.0.13`.
