### ISSUE TITLE
why the table tree column always shown in the first column?

### ISSUE THREAD

**Issue by neil-dang** [foolishchow/element-tree-grid#3]
![image](https://cloud.githubusercontent.com/assets/13329344/25653943/b4866bc4-3021-11e7-9a2e-f73a4da16f94.png)
![image](https://cloud.githubusercontent.com/assets/13329344/25653957/c4b9fa38-3021-11e7-93d5-887373234d58.png)

**Comment by foolishchow** [comment]
this bug is fixed @neil-dang  , update your `element-tree-grid` to version `0.0.7`

**Comment by neil-dang** [comment]
I only can get v0.0.6
![image](https://cloud.githubusercontent.com/assets/13329344/25731278/80dd9a7a-3177-11e7-8e09-e75b5d74306a.png)
I found ':expand-all="!!1"' in your example code, is this for expanded by default?

**Comment by foolishchow** [comment]
now [`element-tree-grid@0.0.8`][link] is available    

checkout your `package.json` , and check `element-tree-grid` version 

[link]: https://www.npmjs.com/package/element-tree-grid '0.0.8'
