### ISSUE TITLE
v0.0.12 still have repeated bug, and wrong hierarchy

### ISSUE THREAD

**Issue by insub** [foolishchow/element-tree-grid#5]
On 0.0.12 version, i found still have repeated bug, and wrong hierarchy.
And if i use element el-tree , everything is ok. So i guess the data is valid.

My tree data json is here:
`
[ { "id": 1, "label": "root", "value": { "data": [ { "name": "gm", "age": 19, "hobby": { "aa": 11, "bb": 22 } } ], "state": 0 }, "remark": "", "type": "object", "oriType": "object", "children": [ { "id": 2, "label": "data", "value": [ { "name": "gm", "age": 19, "hobby": { "aa": 11, "bb": 22 } } ], "remark": "", "type": "array<object>", "oriType": "array<object>", "subType": "object", "children": [ { "id": 4, "label": "name", "value": "gm", "remark": "", "type": "string", "oriType": "string", "children": [] }, { "id": 5, "label": "age", "value": 19, "remark": "", "type": "number", "oriType": "number", "children": [] }, { "id": 6, "label": "hobby", "value": { "aa": 11, "bb": 22 }, "remark": "", "type": "object", "oriType": "object", "children": [ { "id": 7, "label": "aa", "value": 11, "remark": "", "type": "number", "oriType": "number", "children": [] }, { "id": 8, "label": "bb", "value": 22, "remark": "", "type": "number", "oriType": "number", "children": [] } ] } ] }, { "id": 9, "label": "state", "value": 0, "remark": "", "type": "number", "oriType": "number", "children": [] } ] } ]`

**Comment by foolishchow** [comment]
you must has an `parent_key` in `children` item , or there will be problems in expand

**Comment by insub** [comment]
@foolishchow thank~
